### ISSUE TITLE
Async_continue not working with sinatra 1.2.0

### ISSUE THREAD

**Issue by PatrickLef** [raggi/async_sinatra#12]
https://github.com/sinatra/sinatra/commit/4d0b7403ac5247eb67099a7bc6c632609c8439de#lib/sinatra/base.rb

Makes async_continue break.
app.options.async_schedules.shift
on line 81 in async/test

**Comment by tadast** [comment]
In case anyone else is getting this error with the latest version of the gem, make sure your RACK_ENV environment variable set to 'test'.
