### ISSUE TITLE
testing async sinatra app in rails 3

### ISSUE THREAD

**Issue by ayamomiji** [raggi/async_sinatra#13]
full codes: https://gist.github.com/867967

i tried modify lib/sinatra/async/test.rb:81 from `options` to `settings`, but it failed with:
    NoMethodError:
       undefined method `async_schedules' for AsyncTest:Class
     # /home/ayaya/.rvm/gems/ruby-1.9.2-p180/gems/async_sinatra-0.5.0/lib/sinatra/async/test.rb:81:in`async_continue'
     # /home/ayaya/.rvm/gems/ruby-1.9.2-p180/gems/async_sinatra-0.5.0/lib/sinatra/async/test.rb:59:in `aget'
     # ./spec/metals/async_test_spec.rb:14:in`block (3 levels) in <top (required)>'

**Comment by rafaltrojanowski** [comment]
@ayamomiji Did you fix it? I have this error (master)
